### ISSUE TITLE
주문 모델

### ISSUE THREAD

**Issue by makemyway-kr** [ssunivs/New-ssunivs-store#7]
주문 모델 basic하게 작성했는데 혹시 더 들어가거나 수정해야할게 있을까요?

**Comment by clroot** [comment]
- purcahse > order 로 이름 변경
- purcahse.customer > sqlalchemy의 relationship api 중 OneToOne 연관관계 찾아서 적용할 것
- purchase_good > order_good 으로 이름 변경 및 OneToMay, ManyToOne 연간관계 찾아서 적용할 것

-> ORM을 쓰는데, 연관관계 없이 외래키만 저장하면, ORM의 메리트를 많이 날려먹는 것(연관된 row 조회할 때, 외래키 이용해서 다시 쿼리 날려야하는 번거로움)
-> ORM으로 연관관계 잘 매핑해놓으면, 객체 조회 시, 연관된 객체 동시에 조회 or LAZY하게 조회 가능
